# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('meal_type', models.CharField(choices=[('MC', 'Main Courses'), ('AP', 'Appetizer'), ('DE', 'Dessert')], default='MC', max_length=2)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('ingredients', models.ManyToManyField(blank=True, to='Menu.Ingredient')),
            ],
            options={
                'ordering': ('meal_type',),
            },
        ),
    ]
