# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20161127_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
