# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:18
from __future__ import unicode_literals

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_meal_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image_url',
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to=Menu.models.upload_to),
        ),
    ]
