# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nif',
            field=models.IntegerField(blank=True),
        ),
    ]
