# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20161116_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nif',
            field=models.IntegerField(null=True),
        ),
    ]
