# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20161116_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserProfile',
        ),
    ]
