# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20161126_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nif',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$')]),
        ),
    ]
